import type {ClaimPortalsDashboard} from '../../types/claimPortals';

export const CLAIM_PORTALS_DASHBOARD: ClaimPortalsDashboard = {
  stats: {
    total: 28,
    active: 24,
    inactive: 4,
    newThisMonth: 8,
    businessRequests: 5,
    trends: {
      total: -20,
      active: -30,
      inactive: 100,
      newThisMonth: -20,
      businessRequests: 44.4,
    },
  },
  requestSummary: {
    total: 5,
    pending: 2,
    approved: 2,
    rejected: 1,
  },
  drawerBadges: {
    businessRequests: 4,
    contactRequests: 11,
  },
  portals: [
    {
      id: 'cp-1001',
      name: 'test ARCSK',
      businessId: '562464',
      status: 'active',
      createdAt: '2026-09-02',
      linkedBusinesses: 11,
      documents: 4,
      assignedUsers: 10,
      isNewThisMonth: true,
    },
    {
      id: 'cp-1002',
      name: 'CLANEWWWWWW',
      businessId: '882104',
      status: 'active',
      createdAt: '2026-08-21',
      linkedBusinesses: 3,
      documents: 2,
      assignedUsers: 6,
      isNewThisMonth: false,
    },
    {
      id: 'cp-1003',
      name: 'AARMS',
      businessId: '441902',
      status: 'inactive',
      createdAt: '2026-07-14',
      linkedBusinesses: 1,
      documents: 0,
      assignedUsers: 2,
      isNewThisMonth: false,
    },
    {
      id: 'cp-1004',
      name: 'Summit Claims Group',
      businessId: '710338',
      status: 'active',
      createdAt: '2026-09-01',
      linkedBusinesses: 8,
      documents: 5,
      assignedUsers: 12,
      isNewThisMonth: true,
    },
    {
      id: 'cp-1005',
      name: 'Northwind Adjusters',
      businessId: '229871',
      status: 'active',
      createdAt: '2026-06-18',
      linkedBusinesses: 5,
      documents: 3,
      assignedUsers: 7,
      isNewThisMonth: false,
    },
    {
      id: 'cp-1006',
      name: 'Harbor Point Risk',
      businessId: '993120',
      status: 'inactive',
      createdAt: '2026-05-09',
      linkedBusinesses: 2,
      documents: 1,
      assignedUsers: 3,
      isNewThisMonth: false,
    },
    {
      id: 'cp-1007',
      name: 'Lakeside Mutual',
      businessId: '156774',
      status: 'active',
      createdAt: '2026-08-30',
      linkedBusinesses: 9,
      documents: 6,
      assignedUsers: 14,
      isNewThisMonth: false,
    },
    {
      id: 'cp-1008',
      name: 'Pioneer Loss Services',
      businessId: '604551',
      status: 'active',
      createdAt: '2026-09-03',
      linkedBusinesses: 4,
      documents: 2,
      assignedUsers: 5,
      isNewThisMonth: true,
    },
    {
      id: 'cp-1009',
      name: 'Cedar Ridge Claims',
      businessId: '318206',
      status: 'active',
      createdAt: '2026-04-22',
      linkedBusinesses: 6,
      documents: 4,
      assignedUsers: 8,
      isNewThisMonth: false,
    },
    {
      id: 'cp-1010',
      name: 'Atlas Business Portal',
      businessId: '775430',
      status: 'inactive',
      createdAt: '2026-03-11',
      linkedBusinesses: 0,
      documents: 1,
      assignedUsers: 1,
      isNewThisMonth: false,
    },
    {
      id: 'cp-1011',
      name: 'Blue Oak Partners',
      businessId: '501992',
      status: 'active',
      createdAt: '2026-09-04',
      linkedBusinesses: 7,
      documents: 3,
      assignedUsers: 9,
      isNewThisMonth: true,
    },
    {
      id: 'cp-1012',
      name: 'Evergreen Field Ops',
      businessId: '846013',
      status: 'active',
      createdAt: '2026-07-28',
      linkedBusinesses: 10,
      documents: 8,
      assignedUsers: 15,
      isNewThisMonth: false,
    },
  ],
};
