import type {IntakeConfig, IntakeOption} from '../../types/intake';

const toOptions = (values: string[]): IntakeOption[] =>
  values.map(value => ({id: value, label: value}));

export const INTAKE_CONFIG: IntakeConfig = {
  requiredHint: 'Fields marked * are required.',
  nextLabel: 'Next',
  previousLabel: 'Previous',
  submitLabel: 'Submit Intake',
  submitTitle: 'Submit this intake?',
  submitMessage:
    'Double-check the reporter, incident, and driver details. You can still edit after the live API is connected.',
  discardTitle: 'Discard intake?',
  discardMessage: 'Your entries on this claim will be lost.',
  steps: [
    {
      id: 'reporter',
      title: 'Reporter',
      cardTitle: 'Reporter Information',
      subtitle: 'Who is calling this in',
      fields: [
        {
          id: 'portalId',
          label: 'Related portal',
          type: 'portal',
          required: true,
          validation: ['required'],
        },
        {
          id: 'reportedBy',
          label: 'Reported by',
          type: 'select',
          required: true,
          validation: ['required'],
          options: toOptions(['Driver', 'Customer', 'Police', 'Witness', 'Other']),
        },
        {
          id: 'driverType',
          label: 'Driver type',
          type: 'select',
          required: true,
          validation: ['required'],
          options: toOptions([
            'Company driver',
            'Owner operator',
            'Contractor',
            'Third party',
          ]),
        },
        {
          id: 'callerTitle',
          label: 'Caller title',
          type: 'text',
          placeholder: 'Dispatcher',
          row: 'caller-identity',
        },
        {
          id: 'callerName',
          label: 'Caller name',
          type: 'text',
          placeholder: 'Full name',
          autoCapitalize: 'words',
          row: 'caller-identity',
        },
        {
          id: 'callerEmail',
          label: 'Caller email',
          type: 'email',
          placeholder: 'name@example.com',
          validation: ['email'],
          autoCapitalize: 'none',
        },
        {
          id: 'callerPhone',
          label: 'Caller phone',
          type: 'phone',
          hint: 'Up to 15 digits.',
          validation: ['phone'],
        },
      ],
    },
    {
      id: 'timeline',
      title: 'Timeline',
      cardTitle: 'Incident Timeline',
      subtitle: 'When the incident happened',
      fields: [
        {
          id: 'incidentDate',
          label: 'Date of incident',
          type: 'date',
          required: true,
          placeholder: 'Select date',
          validation: ['required', 'date'],
          row: 'when',
        },
        {
          id: 'incidentTime',
          label: 'Time of incident',
          type: 'time',
          required: true,
          placeholder: 'Select time',
          validation: ['required', 'time'],
          row: 'when',
        },
        {
          id: 'timeZone',
          label: 'Time zone',
          type: 'select',
          defaultValue: 'America/New_York',
          options: toOptions([
            'America/New_York',
            'America/Chicago',
            'America/Denver',
            'America/Los_Angeles',
            'UTC',
          ]),
        },
      ],
    },
    {
      id: 'incident',
      title: 'Incident',
      cardTitle: 'Incident Information',
      subtitle: 'What happened and why',
      fields: [
        {
          id: 'claimType',
          label: 'Claim type',
          type: 'select',
          required: true,
          validation: ['required'],
          options: toOptions(['Auto', 'Cargo', 'Property', 'Liability', 'Injury']),
          row: 'claim-issue',
        },
        {
          id: 'issueType',
          label: 'Issue type',
          type: 'select',
          options: toOptions(['Accident', 'Theft', 'Damage', 'Delay', 'Injury']),
          row: 'claim-issue',
        },
        {
          id: 'deliveryInstructions',
          label: 'Customer delivery instructions',
          type: 'textarea',
          placeholder: 'Gate codes, dock hours, contacts...',
        },
        {
          id: 'lossType',
          label: 'Loss type',
          type: 'select',
          options: toOptions(['Collision', 'Overturn', 'Fire', 'Weather', 'Theft']),
          row: 'loss-road',
        },
        {
          id: 'roadway',
          label: 'Roadway',
          type: 'select',
          options: toOptions([
            'Interstate',
            'Highway',
            'City street',
            'Parking lot',
            'Terminal',
          ]),
          row: 'loss-road',
        },
        {
          id: 'weather',
          label: 'Weather',
          type: 'select',
          options: toOptions(['Clear', 'Rain', 'Snow', 'Fog', 'Ice']),
        },
        {
          id: 'vehiclesInvolved',
          label: 'Vehicles involved',
          type: 'select',
          options: toOptions(['1', '2', '3', '4+']),
          row: 'counts',
        },
        {
          id: 'peopleInvolved',
          label: 'People involved',
          type: 'select',
          options: toOptions(['1', '2', '3', '4+']),
          row: 'counts',
        },
        {
          id: 'incidentPlace',
          label: 'Where did the incident occur?',
          type: 'select',
          options: toOptions([
            'On road',
            'Customer location',
            'Terminal',
            'Warehouse',
            'Other',
          ]),
        },
        {
          id: 'accidentDetails',
          label: 'Accident details',
          type: 'textarea',
          placeholder: 'Describe what happened...',
        },
        {
          id: 'actionItems',
          label: 'Action items',
          type: 'textarea',
          placeholder: 'Next steps, towing, notices...',
        },
      ],
    },
    {
      id: 'location',
      title: 'Location',
      cardTitle: 'Incident location',
      subtitle: 'Where the incident occurred',
      fields: [
        {
          id: 'addressLookup',
          label: 'Address lookup',
          type: 'text',
          placeholder: 'Start typing an address',
          hint: 'Use this if you have the full location handy.',
        },
        {
          id: 'region',
          label: 'Region',
          type: 'select',
          options: toOptions(['North', 'South', 'East', 'West', 'Central']),
          row: 'region-country',
        },
        {
          id: 'country',
          label: 'Country',
          type: 'select',
          defaultValue: 'United States',
          options: toOptions(['United States', 'Canada', 'Mexico']),
          row: 'region-country',
        },
        {
          id: 'state',
          label: 'State',
          type: 'select',
          options: toOptions([
            'Alabama',
            'Alaska',
            'Arizona',
            'California',
            'Colorado',
            'Florida',
            'Georgia',
            'Illinois',
            'New York',
            'Texas',
            'Washington',
            'Other',
          ]),
        },
        {
          id: 'city',
          label: 'City',
          type: 'text',
          required: true,
          placeholder: 'City',
          autoCapitalize: 'words',
          validation: ['required'],
          row: 'city-zip',
        },
        {
          id: 'zip',
          label: 'Zip',
          type: 'text',
          placeholder: 'ZIP',
          row: 'city-zip',
        },
        {
          id: 'street',
          label: 'Street / Address',
          type: 'text',
          placeholder: 'Street address',
        },
        {
          id: 'contractorShortCode',
          label: 'Contractor code',
          type: 'text',
          placeholder: 'Optional',
          autoCapitalize: 'characters',
          row: 'contractor',
        },
        {
          id: 'station',
          label: 'Station',
          type: 'text',
          placeholder: 'Optional',
          row: 'contractor',
        },
      ],
    },
    {
      id: 'driver',
      title: 'Driver',
      cardTitle: 'Involved Driver',
      subtitle: 'Who was involved',
      review: {
        title: 'Quick review',
        hint: 'Confirm these details, then add the driver and submit.',
        rows: [
          {id: 'reported', label: 'Reported by', fieldIds: ['reportedBy']},
          {
            id: 'when',
            label: 'When',
            fieldIds: ['incidentDate', 'incidentTime'],
            separator: ' · ',
          },
          {
            id: 'claim',
            label: 'Claim',
            fieldIds: ['claimType', 'issueType'],
            separator: ' · ',
          },
          {
            id: 'city',
            label: 'City',
            fieldIds: ['city', 'state'],
            separator: ', ',
          },
        ],
      },
      fields: [
        {
          id: 'driverId',
          label: 'Driver ID',
          type: 'text',
          placeholder: 'ID',
          row: 'ids',
        },
        {
          id: 'vin',
          label: 'VIN',
          type: 'text',
          placeholder: 'VIN',
          autoCapitalize: 'characters',
          row: 'ids',
        },
        {
          id: 'trackingNumber',
          label: 'Tracking number',
          type: 'text',
          placeholder: 'Load or tracking number',
        },
        {
          id: 'driverFirstName',
          label: 'First name',
          type: 'text',
          required: true,
          placeholder: 'First name',
          autoCapitalize: 'words',
          validation: ['required'],
          row: 'driver-name',
        },
        {
          id: 'driverLastName',
          label: 'Last name',
          type: 'text',
          placeholder: 'Last name',
          autoCapitalize: 'words',
          row: 'driver-name',
        },
        {
          id: 'driverEmail',
          label: 'Email',
          type: 'email',
          placeholder: 'name@example.com',
          validation: ['email'],
          autoCapitalize: 'none',
        },
        {
          id: 'driverMobile',
          label: 'Mobile',
          type: 'phone',
          hint: 'Up to 15 digits.',
          validation: ['phone'],
        },
        {
          id: 'hasCoDriver',
          label: 'Co-driver',
          type: 'select',
          defaultValue: 'No',
          options: toOptions(['No', 'Yes']),
        },
        {
          id: 'coDriverFirstName',
          label: 'Co-driver first name',
          type: 'text',
          required: true,
          placeholder: 'First name',
          autoCapitalize: 'words',
          validation: ['required'],
          visibleWhen: {field: 'hasCoDriver', equals: 'Yes'},
          row: 'codriver',
        },
        {
          id: 'coDriverLastName',
          label: 'Co-driver last name',
          type: 'text',
          placeholder: 'Last name',
          autoCapitalize: 'words',
          visibleWhen: {field: 'hasCoDriver', equals: 'Yes'},
          row: 'codriver',
        },
      ],
    },
  ],
};
